const fs = require('fs');
const path = require('path');
const babel = require('@babel/core');

const rootDir = path.resolve(__dirname, '..');
const webDir = path.join(rootDir, 'web_app');
const outDir = path.join(webDir, 'dist');
const outFile = path.join(outDir, 'app.bundle.js');

const inputs = [
  'app.js',
  'components/shared.jsx',
  'components/quiz.jsx',
  'components/student.jsx',
  'components/teacher.jsx',
  'components/parent.jsx',
  'components/admin.jsx',
  'main.jsx',
];

const banner = `// Tusyen web app bundle.
// Generated by scripts/build-web-app.js. Do not edit this file directly.
`;

function compileFile(relativePath) {
  const absolutePath = path.join(webDir, relativePath);
  const source = fs.readFileSync(absolutePath, 'utf8');
  const result = babel.transformSync(source, {
    filename: absolutePath,
    babelrc: false,
    configFile: false,
    sourceType: 'script',
    presets: [
      ['@babel/preset-react', { runtime: 'classic', development: false }],
    ],
    comments: true,
    compact: false,
  });

  return [
    `// BEGIN ${relativePath}`,
    '(function () {',
    '"use strict";',
    result.code,
    '}());',
    `// END ${relativePath}`,
    '',
  ].join('\n');
}

fs.mkdirSync(outDir, { recursive: true });
const chunks = inputs.map(compileFile);
fs.writeFileSync(outFile, `${banner}\n${chunks.join('\n')}`, 'utf8');

const sizeKb = (fs.statSync(outFile).size / 1024).toFixed(1);
console.log(`Built ${path.relative(rootDir, outFile)} (${sizeKb} KiB)`);
